import pylast

from db.db import *
from config import Config

logging.basicConfig(level=logging.DEBUG)

config = Config()

network = pylast.LastFMNetwork(api_key=config.lastfm.api_key, api_secret=config.lastfm.api_secret,
                               username=config.lastfm.username,
                               password_hash=pylast.md5(config.lastfm.password))

db = Database(config.db.driver_name, config.db.url, config.db.driver_lib_path)
db.update_database()

iter = db.get_tracks("Ария")
for i in iter:
    cur = iter.cur
    try:
        track = network.get_track(cur.artist, cur.title)
        play_cnt = track.get_playcount()
        logging.debug(F"From Last.Fm: Track {track}, play count {play_cnt}")
        db.update_track_play_count(cur.id_, play_cnt)
    except Exception as e:
        logging.error(e)

iter.close()

db.clear_playlist()
playListId = db.add_playlist('admin', False, 'Ария зе бест', 'autogenerated')

iter = db.get_artist_top_tracks('Ария', config.top_artist_songs_playlist.playlist_max_length)
top = []
for s in iter:
    top.append(iter.cur)

db.fill_playlist(playListId, top)
iter.close()
